<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bernstein: Deployment Management Application</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<div id="main_logo">
    <a href="#">Bernstein</a>
</div>

<div>
    <a href="#">Jobs</a> <br>
    <a href="#">Deploy</a> <br>
    <a href="#">Versions</a> <br>
    <a href="#">Admin</a> <br>
</div>

<span class="artifact">Artifact name</span> <br>
<a href="#" class="deploy_info_link">
    <div class="deploy failure">
        <span class="environment">Environment</span> <br>
        <span class="status">Job Status</span> <br>
        <span class="version">Version</span> <br>
    </div>
</a>
<div class="deploy inprogress">
    <span class="environment">Environment</span> <br>
    <span class="status">Job Status</span> <br>
    <span class="version">Version</span> <br>
</div>
<div class="deploy success">
    <span class="environment">Environment</span> <br>
    <span class="status">Job Status</span> <br>
    <span class="version">Version</span> <br>
</div>
</body>

</html>